name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Print Go Envs
      run: go env
        
    - name: Build for ubuntu
      working-directory: ./uuidgen
      run: go build -v -o ./cmd/bin/uuidgen ./cmd/uuidgen.go

    - name: Build for windows amd64
      working-directory: ./uuidgen
      run: GOOS=windows GOARCH=amd64 go build -v -o ./cmd/bin/uuidgen-amd64.exe ./cmd/uuidgen.go

    - name: Archive all binary artifacts
      uses: actions/upload-artifact@v4
      with:
        name: uuidgen-cross-platform-binaries
        path: ./uuidgen/cmd/bin/
        retention-days: 7

    # - name: Test
    #   run: go test -race -v ./...


  release:
    needs: build 
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
    - uses: actions/checkout@v4

    - name: Download all binary artifacts
      uses: actions/download-artifact@v4
      with:
        name: uuidgen-cross-platform-binaries
        path: ./release-artifacts 

    - name: Create GitHub Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        body: |
          This is a new release for version ${{ github.ref_name }}.
          See the changelog for details.
        files: ./release-artifacts/* 