name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.4'

    - name: Print Go Envs
      run: go env

    - name: Print Go Envs
      run: go env
        
    - name: Build
      working-directory: ./uuidgen
      run: go build -v -o ./cmd/uuidgen ./cmd/uuidgen.go

    - name: Test
      run: go test -race -v ./...